@extends('layouts.app')
@section('title', 'Ragav Jyoti Puja & Jyotish Kendra')
@section('content')
<style>
    .home-gallery{display:grid;grid-template-columns:2fr 1fr;gap:12px;padding:12px}.gallery-panel{position:relative;min-height:440px;overflow:hidden;background:#2c1608 url('{{ asset('images/puja-gallery.png') }}') center/cover no-repeat}.gallery-side{display:grid;gap:12px}.gallery-side .gallery-panel{min-height:214px}.gallery-side .gallery-panel:first-child{background-position:24% 48%}.gallery-side .gallery-panel:last-child{background-position:76% 56%}.gallery-panel:after{content:'';position:absolute;inset:0;background:linear-gradient(transparent 38%,rgba(0,0,0,.62))}.gallery-caption{position:absolute;z-index:1;right:28px;bottom:25px;left:28px;color:#fff;font:1.4rem/1.32 Georgia,serif}.gallery-side .gallery-caption{font-size:1.05rem;bottom:20px;left:22px;right:22px}.outline-button{display:inline-flex;margin-top:16px;padding:8px 12px;border:1px solid #fff;color:#fff;font:700 .76rem Arial,sans-serif;text-decoration:none}
    .intro{max-width:880px;margin:68px auto 74px;padding:0 24px;text-align:center}.intro-seal{width:88px;height:88px;margin:0 auto 18px;display:grid;place-items:center;border:3px solid #ef5a00;border-radius:50%;background:#fff7eb;color:#ef5a00;font:2.6rem Georgia,serif}.intro h1{margin-bottom:10px;color:#0a4275;font-size:clamp(2rem,4vw,2.7rem)}.intro p{margin-bottom:6px}.intro-name{font-weight:700}.whatsapp{display:inline-flex;margin-top:14px;padding:11px 17px;background:#22bd67;color:#fff;font-weight:700;text-decoration:none}
    .home-section{max-width:1280px;margin:0 auto 64px;padding:0 24px}.section-head{display:flex;align-items:baseline;justify-content:space-between;gap:20px;margin-bottom:22px}.section-head h2{margin:0;font-size:1.18rem;letter-spacing:.05em;text-transform:uppercase}.section-head a{color:#d95405;font-size:.78rem;text-decoration:none}.service-grid{display:grid;grid-template-columns:repeat(6,minmax(0,1fr));gap:14px}.service-tile{min-height:170px;display:flex;align-items:end;padding:18px;background:linear-gradient(180deg,#ffc45c,#7e5018);color:#fff;font:1.1rem Georgia,serif;text-decoration:none}
    .work-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:18px}.work-card{overflow:hidden;border:1px solid #e6e6e6;background:#fff}.work-image{height:156px;background:url('{{ asset('images/puja-gallery.png') }}') center/cover no-repeat}.work-card:nth-child(2) .work-image{background-position:30% center}.work-card:nth-child(3) .work-image{background-position:64% center}.work-card:nth-child(4) .work-image{background-position:90% center}.work-copy{min-height:122px;padding:16px}.work-copy a{color:#db5908;font-family:Georgia,serif}.work-copy p{margin:10px 0 0;color:#6a6f75;font-size:.82rem}.mini-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:18px}.mini-card{min-height:200px;border:1px solid #e6e6e6;background:#fff}.mini-date{display:block;padding:16px;font-weight:700}.mini-art{height:120px;background:url('{{ asset('images/puja-gallery.png') }}') 70% center/cover no-repeat}.mini-card:nth-child(2) .mini-art{background-position:35% center}.mini-card:nth-child(3) .mini-art{background-position:12% center}.mini-card:nth-child(4) .mini-art{background-position:85% center}
    .feedback{max-width:850px;margin:0 auto 70px;padding:0 24px;text-align:center}.feedback h2{font-size:1.15rem;text-transform:uppercase}.feedback blockquote{margin:28px 0 6px;font:1.2rem Georgia,serif}.feedback cite{color:#6a6f75;font-style:normal;font-size:.9rem}
    .posts-layout{display:grid;grid-template-columns:minmax(0,3fr) minmax(220px,1fr);gap:28px}.posts-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:18px}.post-card{overflow:hidden;border:1px solid #e6e6e6;background:#fff}.post-image{height:150px;background:url('{{ asset('images/puja-gallery.png') }}') center/cover no-repeat}.post-card:nth-child(2) .post-image{background-position:30% center}.post-card:nth-child(3) .post-image{background-position:64% center}.post-card:nth-child(4) .post-image{background-position:90% center}.post-copy{padding:16px}.post-copy a,.top-articles a{color:#db5908;font-family:Georgia,serif;font-size:1.05rem}.post-copy p{margin:10px 0 0;color:#6a6f75;font-size:.84rem}.post-date{display:block;margin-bottom:8px;color:#7a8086;font-size:.78rem}.top-articles h3{margin-bottom:14px}.top-articles a{display:block;margin-bottom:13px;font-family:Arial,sans-serif;font-size:.9rem}.top-articles a:hover,.post-copy a:hover{color:#a33d00}
    @media(max-width:900px){.service-grid{grid-template-columns:repeat(3,1fr)}.work-grid,.mini-grid{grid-template-columns:repeat(2,1fr)}.posts-layout{grid-template-columns:1fr}}@media(max-width:620px){.home-gallery{grid-template-columns:1fr;padding:0}.gallery-panel{min-height:320px}.gallery-side{grid-template-columns:1fr 1fr}.gallery-side .gallery-panel{min-height:190px}.gallery-caption{font-size:1.1rem;left:18px;right:18px;bottom:18px}.gallery-side .gallery-caption{font-size:.88rem;left:12px;right:12px;bottom:12px}.gallery-side .outline-button{display:none}.intro{margin:48px auto 54px}.home-section{margin-bottom:48px;padding:0 16px}.service-grid{grid-template-columns:repeat(2,1fr);gap:10px}.service-tile{min-height:126px;padding:12px;font-size:.96rem}.work-grid,.mini-grid{grid-template-columns:1fr}.posts-grid{grid-template-columns:1fr}.work-image{height:190px}}
</style>
<section class="home-gallery"><article class="gallery-panel"><div class="gallery-caption">Sacred ceremonies, thoughtfully arranged for your family.<br><a class="outline-button" href="{{ route('pujas.index') }}">EXPLORE PUJAS</a></div></article><div class="gallery-side"><article class="gallery-panel"><div class="gallery-caption">Guidance for important beginnings.<br><a class="outline-button" href="{{ route('astrology') }}">READ MORE</a></div></article><article class="gallery-panel"><div class="gallery-caption">Tradition, care and complete coordination.<br><a class="outline-button" href="{{ route('contact') }}">CONTACT US</a></div></article></div></section>
<section class="intro"><div class="intro-seal">R</div><h1>Ragav Jyoti Puja &amp; Jyotish Kendra</h1><p class="intro-name">By Acharya Rajesh Sharma &amp; Vedic Practitioner Team</p><p>Vedic Puja Services | Muhurat Guidance | Personal Jyotish Consultation</p><p><strong>Contact:</strong> Acharya Rajesh Sharma</p><p><strong>Phone:</strong> <a href="tel:+917974639689">+91 79746 39689</a></p><p><strong>Email:</strong> <a href="mailto:ajaysharmaas.094@gmail.com">ajaysharmaas.094@gmail.com</a></p><p><strong>Service Area:</strong> At Your Home | Temple | Online Consultation</p><a class="whatsapp" href="tel:+917974639689">Call Now: +91 79746 39689</a></section>
<section class="home-section"><div class="section-head"><h2>Our Services ( हमारी सेवाएं )</h2></div><div class="service-grid">@foreach(['Vedic Puja & Anushthan','Muhurat & Shubh Muhurat Guidance','Kundli & Jyotish Consultation','Graha Shanti Puja','Griha Pravesh Puja','Marriage & Vivah Puja','Online Jyotish Consultation'] as $service)<a class="service-tile" href="{{ route('astrology') }}">{{ $service }}</a>@endforeach</div></section>
<section class="home-section"><div class="section-head"><h2>Featured Pujas ( विशेष पूजा )</h2><a href="{{ route('pujas.index') }}">VIEW ALL</a></div><div class="work-grid">@forelse($featured->take(4) as $puja)<article class="work-card"><div class="work-image"></div><div class="work-copy"><a href="{{ route('pujas.show', $puja) }}">{{ $puja->name }}</a><p>{{ $puja->excerpt }}</p></div></article>@empty<p>Our puja catalogue is being prepared.</p>@endforelse</div></section>
<section id="vedic-posts" class="home-section"><div class="section-head"><h2>Vedic Posts ( वैदिक लेख )</h2><a href="{{ route('posts') }}">VIEW ALL</a></div><div class="posts-layout"><div class="posts-grid">@foreach([['muhurat','नई शुरुआत के लिए शुभ मुहूर्त','January 11, 2026','शुभ कार्य के लिए मुहूर्त क्यों जरूरी है और सही समय कैसे चुनें।'],['navgraha','नवग्रहों के स्वरूप और उनका फल','March 15, 2024','नवग्रहों का जीवन पर प्रभाव और उनसे जुड़ी सरल जानकारी।'],['vastu','वास्तु के सरल उपाय','July 21, 2024','घर में सकारात्मक ऊर्जा और शांति बनाए रखने के उपयोगी उपाय।'],['family-puja','परिवार की पूजा की तैयारी','July 1, 2024','पूजा से पहले आवश्यक सामग्री, संकल्प और तैयारी की जानकारी।']] as [$slug,$title,$date,$description])<article class="post-card"><div class="post-image"></div><div class="post-copy"><span class="post-date">{{ $date }}</span><a href="{{ route('astrology', ['guidance' => $slug]) }}">{{ $title }}</a><p>{{ $description }}</p></div></article>@endforeach</div><aside class="top-articles"><h3>Top Articles</h3><a href="{{ route('astrology', ['guidance' => 'muhurat']) }}">नई शुरुआत के लिए शुभ मुहूर्त</a><a href="{{ route('astrology', ['guidance' => 'navgraha']) }}">नवग्रहों का स्वरूप और उनका फल</a><a href="{{ route('astrology', ['guidance' => 'vastu']) }}">वास्तु के सरल उपाय</a><a href="{{ route('astrology', ['guidance' => 'family-puja']) }}">परिवार की पूजा की तैयारी</a></aside></div></section>
<section class="feedback"><h2>Feedback ( प्रतिक्रिया )</h2>@forelse($testimonials as $testimonial)<blockquote>“{{ $testimonial->quote }}”</blockquote><cite>— {{ $testimonial->name }}@if($testimonial->city), {{ $testimonial->city }}@endif</cite>@empty<blockquote>“A thoughtful, clear and deeply comforting experience.”</blockquote><cite>— Ragav Jyoti family</cite>@endforelse</section>
@endsection
