<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>@yield('title', 'Raghav Puja & Jyotish Kendra')</title>
    @yield('meta')
    <style>
        :root { color: #1b2430; background: #fff; font-family: Arial, Helvetica, sans-serif; }
        * { box-sizing: border-box; } html { scroll-behavior: smooth; } body { margin: 0; line-height: 1.5; } a { color: inherit; } button, input, textarea { font: inherit; }
        .nav { background: #ef5a00; color: #fff; } .nav-inner { max-width: 1380px; min-height: 72px; margin: auto; padding: 10px 28px; display: flex; align-items: center; justify-content: space-between; gap: 24px; }
        .brand { color: #fff; font-family: Georgia, serif; font-size: 1.45rem; font-weight: 700; line-height: 1.05; text-decoration: none; } .brand small { display: block; margin-top: 5px; font-family: Arial, Helvetica, sans-serif; font-size: .76rem; font-weight: 400; letter-spacing: .08em; }
        .top-actions { display: flex; align-items: center; gap: 22px; font-size: .94rem; } .top-actions a { color: #fff; text-decoration: none; white-space: nowrap; } .top-actions a:hover { text-decoration: underline; } .logout { padding: 0; border: 0; background: transparent; color: #fff; cursor: pointer; }
        .button { display: inline-flex; align-items: center; justify-content: center; min-height: 40px; padding: 9px 16px; border: 1px solid #fff; background: transparent; color: #fff; cursor: pointer; font-weight: 700; text-decoration: none; } .button:hover { background: #fff; color: #d84f00; } .button.secondary { border-color: #e95b09; color: #e95b09; } .button.secondary:hover { background: #e95b09; color: #fff; } .button.whatsapp-button { border-color: #25d366; background: #25d366; color: #fff; } .button.whatsapp-button:hover { border-color: #128c4a; background: #128c4a; color: #fff; } .contact-actions { display: flex; flex-wrap: wrap; gap: 10px; }
        .container { max-width: 1120px; margin: 0 auto; padding: 42px 24px; } .card { background: #fff; border: 1px solid #e6e6e6; border-radius: 2px; padding: 22px; } .auth-card { max-width: 540px; margin: 30px auto; } h1, h2, h3, p { margin-top: 0; } h1 { font-size: 2rem; } h2 { font-size: 1.3rem; } h3 { font-size: 1.05rem; }
        label { display: block; margin: 16px 0 6px; font-weight: 700; font-size: .92rem; } input, textarea { width: 100%; border: 1px solid #c9c9c9; border-radius: 2px; padding: 11px 12px; background: #fff; } textarea { min-height: 85px; resize: vertical; }.check { display: flex; gap: 9px; align-items: flex-start; margin-top: 18px; font-size: .9rem; } .check input { width: auto; margin-top: 3px; }
        .button.full { width: 100%; margin-top: 22px; background: #e95b09; border-color: #e95b09; color: #fff; }.alert { padding: 12px 15px; border-radius: 2px; margin-bottom: 18px; } .success { background: #e6f6e9; color: #1d6537; } .warning { background: #fff5da; color: #715300; } .errors { background: #fff0f0; color: #a42a2a; } .errors ul { margin: 0; padding-left: 20px; } .field-error { display: block; color: #b42318; font-size: .82rem; margin-top: 5px; } .invalid { border-color: #d92d20; }
        .grid { display: grid; grid-template-columns: repeat(3, minmax(0, 1fr)); gap: 24px; }.stat { font-size: 2.3rem; font-weight: 800; color: #e95b09; margin: 5px 0; } .muted { color: #66707a; }.profile dl { margin: 0; } .profile dt { font-size: .8rem; color: #65766b; margin-top: 15px; text-transform: uppercase; letter-spacing: .04em; } .profile dd { margin: 4px 0 0; font-weight: 600; }
        .home-footer { padding: 42px 24px; background: #ffe0a9; text-align: center; }.home-footer nav { display: flex; justify-content: center; flex-wrap: wrap; gap: 12px 24px; margin-bottom: 22px; }.home-footer a { color: #b84a05; }.home-footer p { margin: 0; color: #6b6256; }
        table { width: 100%; border-collapse: collapse; } th, td { text-align: left; padding: 12px 8px; border-bottom: 1px solid #edf1ee; } th { color: #66756b; font-size: .78rem; text-transform: uppercase; }.badge { font-size: .75rem; font-weight: 800; border-radius: 99px; padding: 5px 8px; text-transform: uppercase; }.paid { background: #e5f6e9; color: #25713f; }.pending { background: #fff4d8; color: #856000; }.failed { background: #ffe8e8; color: #a33030; }
        @media (max-width: 850px) { .nav-inner { padding: 13px 18px; align-items: flex-start; } .top-actions { flex-wrap: wrap; justify-content: flex-end; gap: 8px 14px; } .grid { grid-template-columns: repeat(2, minmax(0, 1fr)); } } @media (max-width: 560px) { .nav-inner { display: block; padding: 16px; } .brand { display: block; margin-bottom: 18px; } .top-actions { display: grid; grid-template-columns: repeat(2, minmax(0, 1fr)); justify-content: initial; gap: 8px; font-size: .9rem; } .top-actions a, .top-actions form { min-width: 0; } .top-actions a, .top-actions .logout { display: flex; align-items: center; min-height: 42px; padding: 8px 10px; border: 1px solid rgba(255,255,255,.35); } .top-actions .logout { width: 100%; } .container { padding: 28px 16px; } .grid { grid-template-columns: 1fr; } .contact-actions .button { width: 100%; } }
    </style>
</head>
<body>
<nav class="nav"><div class="nav-inner"><a class="brand" href="{{ route('home') }}">Raghav<small>Puja &amp; Jyotish Kendra</small></a><div class="top-actions"><a href="{{ route('home') }}">Home</a><a href="{{ route('pujas.index') }}">Pujas</a><a href="{{ route('services') }}">Services</a><a href="{{ route('posts') }}">Posts</a><a href="{{ route('astrologers') }}">Our Acharyas</a><a href="{{ route('mahakal.darshan') }}">Mahakal Darshan</a><a href="{{ route('contact') }}">Contact</a>@auth <form method="POST" action="{{ route('logout') }}">@csrf<button class="logout">Log out</button></form>@else <a href="{{ route('login') }}">Sign in</a>@endauth</div></div></nav>
<main>@if(session('success')) <div class="container"><div class="alert success">{{ session('success') }}</div></div> @endif @if(session('warning')) <div class="container"><div class="alert warning">{{ session('warning') }}</div></div> @endif @yield('content')</main>
<footer class="home-footer"><nav><a href="{{ route('astrologers') }}">About Us</a><a href="{{ route('contact') }}">Contact</a><a href="{{ route('pujas.index') }}">Pujas</a><a href="{{ route('astrology') }}">Astrology</a></nav><p>&copy; {{ date('Y') }} Raghav Puja &amp; Jyotish Kendra</p></footer>
</body>
</html>
